#!/usr/bin/expect -f

spawn "/usr/share/forticlient/opt/forticlient-sslvpn/64bit/forticlientsslvpn_cli" --server $env(VPNADDR) --vpnuser $env(VPNUSER) --keepalive

expect -exact "Password for VPN:" {
  send -- "$env(VPNPASS)\n"
}


expect -exact "Would you like to connect to this server? (Y/N)" {
  send -- "Y\n"
}

expect "An email message containing a Token Code will be sent to" {
  interact
}

expect -exact "STATUS::Login succeed"
expect -exact "STATUS::Starting PPPd"
expect -exact "STATUS::Initializing tunnel"
expect -exact "STATUS::Connecting to server"